FROM balenalib/armv7hf-debian
MAINTAINER fabrizio2210

ENV APP_FOLDER="/opt/web"
ENV STATIC_FILES_PATH="/static_files"
ENV ETC_FOLDER="/etc/uwsgi"
ENV SOCKET_FOLDER="${ETC_FOLDER}/socket"

RUN [ "cross-build-start" ]

RUN apt-get update && apt-get install -y nginx \
    sed \
    curl \
    supervisor \
    gcc \
    python3.9 \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python-setuptools \
    libpcre3 \
    libpcre3-dev \
    libjpeg-dev \
    zlib1g-dev \
    && apt-get clean


COPY src/ ${APP_FOLDER}/
RUN mkdir ${ETC_FOLDER} && chmod 755 ${ETC_FOLDER} && chown www-data ${ETC_FOLDER}
RUN mkdir ${SOCKET_FOLDER} && chmod 755 ${SOCKET_FOLDER} && chown www-data ${SOCKET_FOLDER}
RUN mkdir ${STATIC_FILES_PATH} && chmod 755 ${STATIC_FILES_PATH} && chown www-data ${STATIC_FILES_PATH}

RUN pip3 install wheel
RUN pip3 install -r ${APP_FOLDER}/requirements.txt

# UWSGI
COPY docker/lib/uwsgi.ini ${ETC_FOLDER}/
RUN sed -i "s|{{ app_folder }}|$APP_FOLDER|g" ${ETC_FOLDER}/uwsgi.ini
RUN sed -i "s|{{ socket_folder }}|$SOCKET_FOLDER|g" ${ETC_FOLDER}/uwsgi.ini

# NGINX
EXPOSE 80
RUN ln -fs /dev/stdout /var/log/nginx/access.log
RUN ln -fs /dev/stdout /var/log/nginx/error.log

COPY docker/lib/web-site.conf /etc/nginx/sites-available/web.conf
RUN sed -i "s|{{ socket_folder }}|$SOCKET_FOLDER|g" /etc/nginx/sites-available/web.conf
RUN ln -s /etc/nginx/sites-available/web.conf /etc/nginx/sites-enabled/web.conf 

RUN rm /etc/nginx/sites-enabled/default

# SUPERVISOR
COPY docker/lib/supervisord-debian.conf /etc/supervisor/conf.d/supervisord.conf
RUN sed -i "s|{{ etc_folder }}|$ETC_FOLDER|g" /etc/supervisor/conf.d/supervisord.conf

RUN [ "cross-build-end" ]

# COMMAND
CMD /usr/bin/supervisord -u root
