FROM debian
MAINTAINER fabrizio2210
ENV DOCKERVERSION=20.10.2
ENV DOCKERARCH=x86_64

ENV APP_FOLDER="/opt/web"
ENV ETC_FOLDER="/etc/uwsgi"
ENV SOCKET_FOLDER="${ETC_FOLDER}/socket"

RUN apt-get update && apt-get install -y nginx \
    sed \
    curl \
    supervisor \
    python3.7 \
    python3-pip \
    python3-setuptools \
    python3-setuptools \
    python-setuptools \
    libpcre3 \
    libpcre3-dev \
    && apt-get clean

RUN curl -fsSLO https://download.docker.com/linux/static/stable/${DOCKERARCH}/docker-${DOCKERVERSION}.tgz \
    && tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 -C /usr/local/bin docker/docker \
    && rm docker-${DOCKERVERSION}.tgz

RUN groupadd -g 136 docker -r && usermod -a -G docker www-data

COPY src/ ${APP_FOLDER}/
RUN mkdir ${ETC_FOLDER} && chmod 755 ${ETC_FOLDER} && chown www-data ${ETC_FOLDER}
RUN mkdir ${SOCKET_FOLDER} && chmod 755 ${SOCKET_FOLDER} && chown www-data ${SOCKET_FOLDER}

RUN pip3 install -r ${APP_FOLDER}/requirements.txt

# UWSGI
COPY docker/lib/uwsgi.ini ${ETC_FOLDER}/
RUN sed -i "s|{{ app_folder }}|$APP_FOLDER|g" ${ETC_FOLDER}/uwsgi.ini
RUN sed -i "s|{{ socket_folder }}|$SOCKET_FOLDER|g" ${ETC_FOLDER}/uwsgi.ini

# NGINX
EXPOSE 80

COPY docker/lib/web-site.conf /etc/nginx/sites-available/web.conf
RUN sed -i "s|{{ socket_folder }}|$SOCKET_FOLDER|g" /etc/nginx/sites-available/web.conf
RUN ln -s /etc/nginx/sites-available/web.conf /etc/nginx/sites-enabled/web.conf 

RUN rm /etc/nginx/sites-enabled/default

# SUPERVISOR
COPY docker/lib/supervisord-debian.conf /etc/supervisor/conf.d/supervisord.conf
RUN sed -i "s|{{ etc_folder }}|$ETC_FOLDER|g" /etc/supervisor/conf.d/supervisord.conf

# COMMAND
CMD /usr/bin/supervisord -u root
