FROM debian
MAINTAINER fabrizio2210

ENV APP_FOLDER="/opt/web"

RUN apt-get update && apt-get install -y nginx \
    npm \
    curl

RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs

RUN ln -sf /dev/stdout /var/log/nginx/access.log && ln -sf /dev/stderr /var/log/nginx/error.log

COPY src/vue/ ${APP_FOLDER}/

RUN cd ${APP_FOLDER}/src/ && \
    npm cache clean -f && \
    rm -rf node_modules package-lock.json && \
    npm install && \
    npm run build && \
    cp -r ../dist/* /var/www/html/

# NGINX
EXPOSE 80

COPY docker/lib/frontend-web-site.conf /etc/nginx/sites-available/web.conf
RUN ln -s /etc/nginx/sites-available/web.conf /etc/nginx/sites-enabled/web.conf 
RUN rm /etc/nginx/sites-enabled/default
RUN rm /var/www/html/index.nginx-debian.html

# COMMAND
CMD /usr/sbin/nginx -g 'daemon off;'
