FROM golang

WORKDIR /usr/src/app/printer

RUN go install github.com/githubnemo/CompileDaemon@latest

RUN apt update && apt install -y poppler-utils && apt clean

CMD CompileDaemon -command="./Printer"
