FROM debian
MAINTAINER fabrizio2210

ENV APP_FOLDER="/opt/web"
ENV STATIC_FILES_PATH="/static_files"

RUN apt-get update && apt-get install -y \
    sed \
    curl \
    gcc \
    python3.9 \
    python3-pip \
    python3-dev \
    python3-setuptools \
    python-setuptools \
    libpcre3 \
    libpcre3-dev \
    libjpeg-dev \
    zlib1g-dev \
    && apt-get clean


RUN mkdir ${STATIC_FILES_PATH} && chmod 755 ${STATIC_FILES_PATH} && chown www-data ${STATIC_FILES_PATH}

COPY src/requirements.txt ${APP_FOLDER}/
RUN pip3 install -r ${APP_FOLDER}/requirements.txt

# COMMAND
WORKDIR ${APP_FOLDER}
CMD python3 app.py
